### ISSUE TITLE
Invalid version key

### ISSUE THREAD

**Issue by explosivo22** [sarahhenkens/home-assistant-iocare#20]
Upon initializing, the following error shows up in my log file:

`The custom integration 'iocare' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

I have noticed that the version defined: `2021.4.0` does not match the release version of the integration of `0.0.1`.

[Developer Versions](https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions) says that this should be the standard major, minor and patch version.

**Comment by explosivo22** [comment]
will be fixed with pull release #18 .  I see this now and will close this ticket

**Comment by RobertD502** [comment]
@explosivo22 Yes, this will be fixed with that pull request. The manifest included 2021.4.0 prior to the repo owner creating the 0.0.1 release. The method of versioning was discussed afterwards, so the manifest version doesn't match up with the github release version. A mismatch in version between the manifest file and github release version will not cause Home Assistant to not load the integration- all home assistant cares about is that there is a valid version in the manifest file.

**Comment by explosivo22** [comment]
Very true that home assistant does not care about release version on github, but probably a best practice to keep the two the same for the end user when installing through hacs.  Yes as long as home assistant gets the pull request to fix the version then everything will be great.

**Comment by RobertD502** [comment]
> Very true that home assistant does not care about release version on github, but probably a best practice to keep the two the same for the end user when installing through hacs.  Yes as long as home assistant gets the pull request to fix the version then everything will be great.

I 100% agree. Unfortunately, in the case of this repo, only the repo owner has the ability to merge the pull request- it has been a couple of months so I'm not sure when or if it'll get merged.

**Comment by explosivo22** [comment]
I was noticing that.  I saw another discussion between you two where she was saying that she did not have a lot of time to maintain this any longer.  May need to look into adding other users with read access.  I am hopeful that she will come back to this and help us to get it moving along again

**Comment by RobertD502** [comment]
Hopefully. At the time when she was active, since I was creating a decent amount of PR at the time, I tried to get added as a collaborator, which would have allowed me to merge my pull requests and create releases. I'm not sure if she ever saw that.
