### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by kylerw** [sarahhenkens/home-assistant-iocare#6]
File "/usr/local/lib/python3.7/site-packages/iocare/devices/purifier.py", line 16, in refresh
self.is_on = control_status['0001'] == '1'
KeyError: '0001'

**Comment by kylerw** [comment]
Seems to have been an API issue. Not seeing this any more.

**Comment by DeltaAngle** [comment]
In case anyone else comes across this issue, my problem was caused by one of my purifiers being in an offline state. I reset the wifi connection and verified communication in the IOCare app. Removing and reconfiguring the component fixed the KeyError.
